get_mealplan:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: mealie
    start_date:
      selector:
        date:
    end_date:
      selector:
        date:

get_recipe:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: mealie
    recipe_id:
      required: true
      selector:
        text:

get_recipes:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: mealie

get_specific_recipe:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: mealie
    recipe_name:
      required: true
      selector:
        text:

get_specific_recipes:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: mealie
    recipe_name:
      required: true
      selector:
        text:

get_recipe_calories:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: mealie
    recipe_slug:
      required: true
      selector:
        text:

get_calories_based_filtered_recipes:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: mealie
    max_calories:
      required: true
      selector:
        number:

get_filtered_recipes_by_ingredients:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: mealie
    excluded_ingredients:
      required: true
      selector:
        object:
          type: list

filter_recipes_by_popularity:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: mealie
    min_cooked:
      required: true
      selector:
        number:

filter_recipes:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: mealie
    max_cooking_time:
      required: true
      selector:
        number:

import_recipe:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: mealie
    url:
      required: true
      selector:
        text:
    include_tags:
      selector:
        boolean:

set_random_mealplan:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: mealie
    date:
      selector:
        date:
    entry_type:
      selector:
        select:
          options:
            - breakfast
            - lunch
            - dinner
            - side
          translation_key: mealplan_entry_type

heart_recipe:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: mealie
    recipe_id:
      required: true
      selector:
        text:

unheart_recipe:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: mealie
    recipe_id:
      required: true
      selector:
        text:

set_mealplan:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: mealie
    date:
      selector:
        date:
    entry_type:
      selector:
        select:
          options:
            - breakfast
            - lunch
            - dinner
            - side
          translation_key: mealplan_entry_type
    recipe_id:
      selector:
        text:
    note_title:
      selector:
        text:
    note_text:
      selector:
        text:
